### ISSUE TITLE
2020a: Undefined function 'readdir'

### ISSUE THREAD

**Issue by alhirzel** [janklab/SLF4M#8]
I don't know if this is related to #7, but I believe SLF4M is broken in MATLAB 2020a. I just upgraded from 2018b and now when I execute

```matlab
logger.info('test')
```

I receive

```
Error using logger.internal.LibraryInitializer.initLibrary (line 46)
Invalid default value for property 'initializer' in class 'logger.Logger':
Undefined function 'readdir' for input arguments of type 'char'.

Error in logger.internal.LibraryInitializer (line 12)
      logger.internal.LibraryInitializer.initLibrary;

Error in loggerCallImpl (line 42)
loggerObj = logger.Logger.getLogger(callerId);

Error in logger.info (line 14)
loggerCallImpl('info', msg, varargin);
```

**Comment by alhirzel** [comment]
Nevermind, I'm an idiot, just saw f80e15c7895ad0aeb5d4b4d647604083910dd800 :)

**Comment by apjanke** [comment]
Yep, I think that fixes R2020a.

SLF4M is still totally busted in R2021a and later (see here: https://github.com/janklab/SLF4M/issues/7), because Java logging stuff. Still trying to work that out. Sorry there. Fix soon, I think
